import{a as p,i as l,S as d}from"./assets/vendor-D3PmPE7A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function f(i){const t="https://pixabay.com",o="/api/",n=new URLSearchParams({key:"48867408-88b49db3a4e372b4d460477c4",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${t}${o}?${n}`;return p.get(e).then(r=>r.data.hits).catch(r=>(console.log("Error images:",r),[]))}document.querySelector(".gallery");function h(i){if(gallery.innerHTML="",i.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const t=i.map(({largeImageURL:n,webformatURL:e,tags:r,likes:s,views:u,comments:g,downloads:m})=>`
      <a href="${n}" class="gallery-item">
        <img src="${e}" alt="${r}" />
        <div class="image-info">
          <p><strong>Likes</strong> ${s}</p>
          <p><strong>Views</strong> ${u}</p>
          <p><strong>Comments</strong> ${g}</p>
          <p><strong>Downloads</strong> ${m}</p>
        </div>
      </a>`).join("");gallery.innerHTML=t,new d(".gallery a",{captionsData:"alt",captionPosition:"botton",captionDelay:250,overlayOpacity:.7}).refresh()}const a={form:document.querySelector(".form"),input:document.querySelector(".input"),loader:document.querySelector("#loader"),gallery:document.querySelector(".gallery")};function y(){a.loader.classList.remove("hidden")}function c(){a.loader.classList.add("hidden")}a.form.addEventListener("submit",i=>{i.preventDefault();const t=a.input.value.trim();if(!t){l.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}y(),f(t).then(o=>{c(),o.length===0?l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):h(o)}).catch(o=>{c(),l.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:5e3}),console.error("Error fetching images:",o)}),a.form.reset()});
//# sourceMappingURL=index.js.map
